### ISSUE TITLE
New commands checklist

### ISSUE THREAD

**Issue by defracted** [defracted/galleon#1]
These commands should be added soon:
 - [x] `serverinfo [ID]` — shows general information about the server
 - [x] `todo` — a commands group for todos
 - [x] `avatarcolors <User>` — a command that will tell what colors have been used in someone's avatar, might also use attachments
 - [ ] `urban <text>` — a command that will search for a meaning of the word on urban dictionary (might as well use ext.menus on this one)
- [x] `who` — a little guessing game

**Comment by defracted** [comment]
`urban` is actually not a good idea since it can be very NSFW.
